In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score, calinski_harabasz_score, silhouette_samples
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import files
uploaded = files.upload()

Saving EastWestAirlines.xlsx to EastWestAirlines.xlsx


Standardizing the data:

standard_scaler = StandardScaler()

data = standard_scaler.fit_transform(airline_data)

Normalizing the data:

minmax = MinMaxScaler()

data = minmax.fit_transform(airline_data)

In [8]:
data = pd.read_excel('EastWestAirlines.xlsx', sheet_name = 'data')
data = data.drop(['ID#'],axis=1)
data.head()

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    28143           0          1          1          1          174   
1    19244           0          1          1          1          215   
2    41354           0          1          1          1         4123   
3    14776           0          1          1          1          500   
4    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Balance            3999 non-null   int64
 1   Qual_miles         3999 non-null   int64
 2   cc1_miles          3999 non-null   int64
 3   cc2_miles          3999 non-null   int64
 4   cc3_miles          3999 non-null   int64
 5   Bonus_miles        3999 non-null   int64
 6   Bonus_trans        3999 non-null   int64
 7   Flight_miles_12mo  3999 non-null   int64
 8   Flight_trans_12    3999 non-null   int64
 9   Days_since_enroll  3999 non-null   int64
 10  Award?             3999 non-null   int64
dtypes: int64(11)
memory usage: 343.8 KB


In [36]:
# MinMax
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return (x)

In [11]:
df_norm = norm_func(data)
df_norm.head()

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0  0.016508         0.0       0.00        0.0        0.0     0.000660   
1  0.011288         0.0       0.00        0.0        0.0     0.000815   
2  0.024257         0.0       0.00        0.0        0.0     0.015636   
3  0.008667         0.0       0.00        0.0        0.0     0.001896   
4  0.057338         0.0       0.75        0.0        0.0     0.164211   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0     0.011628           0.000000         0.000000           0.843742     0.0  
1     0.023256           0.000000         0.000000           0.839884     0.0  
2     0.046512           0.000000         0.000000           0.847842     0.0  
3     0.011628           0.000000         0.000000           0.837955     0.0  
4     0.302326           0.067398         0.075472           0.835905     1.0

In [20]:
plt.figure(figsize=(12, 6))
dendrogram = sch.dendrogram(sch.linkage(df_norm, method ='complete'))
plt.show()

In [21]:
# Create Clusters
hc = AgglomerativeClustering(n_clusters = 5, affinity = 'euclidean', linkage = 'complete')
hc

AgglomerativeClustering(affinity='euclidean', linkage='complete', n_clusters=5)

In [23]:
y_hc = hc.fit_predict(df_norm)
data['cluster_id'] = hc.labels_
data

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0       28143           0          1          1          1          174   
1       19244           0          1          1          1          215   
2       41354           0          1          1          1         4123   
3       14776           0          1          1          1          500   
4       97752           0          4          1          1        43300   
...       ...         ...        ...        ...        ...          ...   
3994    18476           0          1          1          1         8525   
3995    64385           0          1          1          1          981   
3996    73597           0          3          1          1        25447   
3997    54899           0          1          1          1          500   
3998     3016           0          1          1          1            0   

      Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  \
0               1                  0                0               7000   
1               2                  0                0               6968   
2               4                  0                0               7034   
3               1                  0                0               6952   
4              26               2077                4               6935   
...           ...                ...              ...                ...   
3994            4                200                1               1403   
3995            5                  0                0               1395   
3996            8                  0                0               1402   
3997            1                500                1               1401   
3998            0                  0                0               1398   

      Award?  cluster_id  
0          0           0  
1          0           0  
2          0           0  
3          0           0  
4          1           1  
...      ...         ...  
3994       1           2  
3995       1           2  
3996       1           2  
3997       0           0  
3998       0           0  

[3999 rows x 12 columns]

# K-Means

In [25]:
from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist
from sklearn.preprocessing import StandardScaler

In [54]:
data2 = pd.read_excel('EastWestAirlines.xlsx', sheet_name = "data")
data2 = data2.drop(['ID#'],axis=1)

In [55]:
scaler = StandardScaler()
scaled_df = scaler.fit_transform(data2)
scaled_df

array([[-4.51140783e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.39545434e+00, -7.66919299e-01],
       [-5.39456874e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.37995704e+00, -7.66919299e-01],
       [-3.20031232e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.41192021e+00, -7.66919299e-01],
       ...,
       [-4.29480975e-05, -1.86298687e-01,  6.83121167e-01, ...,
        -3.62167870e-01, -1.31560393e+00,  1.30391816e+00],
       [-1.85606976e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -9.85033311e-02, -1.31608822e+00, -7.66919299e-01],
       [-7.00507951e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01, -1.31754109e+00, -7.66919299e-01]])

In [45]:
wcss = []
for i in range (1,11):
    kmeans = KMeans(n_clusters = i)
    kmeans.fit(df_norm)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss,color='black')
plt.scatter(range(1,11),wcss,color='red')
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

### Silhouette Score

In [41]:
clust_list = [2,3,4,5,6,7,8,9]

#  Silhouette score
for n in clust_list:
    cluster = KMeans(n_clusters=n)
    cluster_labels = cluster.fit_predict(df_norm)
    sil_score= silhouette_score(df_norm, cluster_labels)
    print("For n_clusters =", n,"The average silhouette_score is :", sil_score)

For n_clusters = 2 The average silhouette_score is : 0.535930510919477
For n_clusters = 3 The average silhouette_score is : 0.4648452938858305
For n_clusters = 4 The average silhouette_score is : 0.47483765255961
For n_clusters = 5 The average silhouette_score is : 0.4430672072796034
For n_clusters = 6 The average silhouette_score is : 0.4021621004641961
For n_clusters = 7 The average silhouette_score is : 0.3904051693222737
For n_clusters = 8 The average silhouette_score is : 0.3801866526571047
For n_clusters = 9 The average silhouette_score is : 0.38427584667302916


According the the silhouette score, the ideal number of clusters is 2.

In [56]:
model = KMeans(n_clusters = 2)
model.fit(df_norm)
x = pd.Series(model.labels_)
data2['cluster'] = x
data2.groupby(data2.cluster).mean()

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  \
cluster                                                              
0        97053.051317  240.196489   2.661715    1.01553   1.018231   
1        59807.839555   87.602462   1.705322    1.01390   1.008737   

          Bonus_miles  Bonus_trans  Flight_miles_12mo  Flight_trans_12  \
cluster                                                                  
0        28905.414585    15.782579         857.501013         2.599595   
1        10227.689039     9.142971         226.292295         0.652502   

         Days_since_enroll  Award?  
cluster                             
0              4625.062120     1.0  
1              3820.652105     0.0

# DBSCAN

In [46]:
from sklearn.cluster import DBSCAN

In [50]:
data3 = pd.read_excel('EastWestAirlines.xlsx', sheet_name = "data")
data3 = data3.drop(['ID#'],axis=1)
data3.head()

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    28143           0          1          1          1          174   
1    19244           0          1          1          1          215   
2    41354           0          1          1          1         4123   
3    14776           0          1          1          1          500   
4    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [51]:
scaled_df

array([[-4.51140783e-01, -1.86298687e-01, -7.69578406e-01, ...,
         1.39545434e+00, -7.66919299e-01, -7.30291870e-01],
       [-5.39456874e-01, -1.86298687e-01, -7.69578406e-01, ...,
         1.37995704e+00, -7.66919299e-01, -7.30291870e-01],
       [-3.20031232e-01, -1.86298687e-01, -7.69578406e-01, ...,
         1.41192021e+00, -7.66919299e-01, -7.30291870e-01],
       ...,
       [-4.29480975e-05, -1.86298687e-01,  6.83121167e-01, ...,
        -1.31560393e+00,  1.30391816e+00,  1.39443508e+00],
       [-1.85606976e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -1.31608822e+00, -7.66919299e-01, -7.30291870e-01],
       [-7.00507951e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -1.31754109e+00, -7.66919299e-01, -7.30291870e-01]])

In [72]:
dbscan = DBSCAN(eps = 1.5, min_samples = 5)
dbscan.fit(scaled_df)
dbscan.labels_

array([0, 0, 0, ..., 1, 0, 0])

In [75]:
db_cluster = pd.Series(dbscan.labels_)
data3['cluster'] = db_cluster
data3.groupby('cluster').mean()

Balance   Qual_miles  cc1_miles  cc2_miles  cc3_miles  \
cluster                                                                
-1       215733.335484  1381.900000   2.764516   1.070968   1.158065   
 0        56525.714641    29.252178   1.684363   1.000000   1.000000   
 1        72115.619200    61.918400   2.632000   1.000000   1.000000   
 2        38556.733333     0.000000   1.000000   2.000000   1.000000   
 3        36524.250000     0.000000   1.000000   3.000000   1.000000   
 4        31161.600000     0.000000   1.000000   2.000000   1.000000   

          Bonus_miles  Bonus_trans  Flight_miles_12mo  Flight_trans_12  \
cluster                                                                  
-1       45721.603226    25.261290        2994.580645         8.758065   
 0        9589.272501     8.728743         173.045209         0.512650   
 1       24773.415200    13.712800         392.944800         1.223200   
 2        8951.533333    12.933333          60.000000         0.400000   
 3       15518.500000    14.500000          50.000000         0.250000   
 4        8723.400000    13.800000         350.000000         1.000000   

         Days_since_enroll    Award?  
cluster                               
-1             4818.754839  0.729032  
 0             3805.321858  0.000000  
 1             4567.045600  1.000000  
 2             3390.400000  0.000000  
 3             3179.625000  0.000000  
 4             3314.800000  1.000000